const members = [
    {   firstname: "",
        surname: "",
        age: "",
        city: "",
        hobby: "",
        favoriteFood: "",
        favoriteVideoGame: "",
        favoriteFilm: "",
        favoriteBook: "",
        petName: "",

    }
    {   firstname: "Willy",
        surname: "Hidalgo",
        age: "25",
        city: "Valencia",
        hobby: "Leer comics",
        favoriteFood: "Postres",
        favoriteVideoGame: "CoD",
        favoriteFilm: "Batman",
        favoriteBook: "Noches oscuras",
        petName: "Buggy",
    }
    },
    {   firstname: "Luis",
        surname: "Tortosa",
        age: "25",
        city: "Salamanca",
        hobby: "Programar",
        favoriteFood: "Cocido madrileño",
        favoriteVideoGame: "Fallout New Vegas",
        favoriteFilm: "Interestellar",
        favoriteBook: "Fight Club",
        petName: "El Picos",
    },
]
